spring:
  application:
    name: "configserver"
  profiles:
    active: git
#    active: native - when doesn't use Github
  cloud:
    config:
      server:
        #        native:
        #          search-locations: "file:///C://Java Springboot//Spring Microservices Set//Section 6//Documents//config"
        #          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/ravindugamage98/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
# Config server data encryption in config-server in github repo
encrypt:
  key: "80348HIEBHFI8BSDWU72808GBU"

server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"